Traceback (most recent call last):
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/Emman/opt/anaconda3/envs/env-jupyterbook/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df = fread("brazil.csv",drop = 1)
df = as_tibble(df)
df_orig = df
------------------

Error in fread("brazil.csv", drop = 1): File 'brazil.csv' does not exist or is non-readable. getwd()=='/Volumes/data/projects/site-jupyterbook/jupyterbook/book/docs'
Traceback:

1. fread("brazil.csv", drop = 1)
2. stop("File '", file, "' does not exist or is non-readable. getwd()=='", 
 .     getwd(), "'")
ERROR: Error in fread("brazil.csv", drop = 1): File 'brazil.csv' does not exist or is non-readable. getwd()=='/Volumes/data/projects/site-jupyterbook/jupyterbook/book/docs'


